name: Run Calculator Tests and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Build the app (if needed)
      - name: Build project
        run: npm run build

      # Step 6: Deploy (example)
      - name: Deploy
        run: |
          echo "Deploying to production..."
          # Example: copy build files to a folder
          mkdir -p C:\deploy-folder
          Copy-Item -Path "dist\*" -Destination "C:\deploy-folder" -Recurse -Force
          echo "Deployment completed!"
