name: Run Calculator Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Optional deploy step (for self-hosted runner)
      - name: Deploy
        run: |
          echo "Deploying..."
          mkdir -p C:\deploy-folder
          Copy-Item -Path "src\*" -Destination "C:\deploy-folder" -Recurse -Force
          echo "Deployment completed!"
